services:
  db:
    container_name: invoiced_db
    build: 
      context: ./db
    image: postgres:15-alpine
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/migration:/db/migration
    restart: always
  api:
    container_name: invoiced
    build: 
      context: ./api
    ports:
      - "9090:${PORT}"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on: 
      - db
    restart: unless-stopped


volumes:
  postgres_data:
    driver: local